# Generated by Django 4.2.30 on 2026-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('room_no', models.CharField(max_length=50)),
                ('shelf_no', models.CharField(max_length=50)),
                ('row', models.CharField(max_length=50)),
                ('column', models.CharField(max_length=50)),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author')),
            ],
        ),
    ]
